### ISSUE TITLE
v0.1.0 release

### ISSUE THREAD

**Issue by TimTaylor** [nhs-r-community/NHSRepisodes#17]
@Lextuga007 - this is probably in a good enough state for a v0.0.1 release. Do you want me to [make one on GitHub](https://github.com/nhs-r-community/NHSRepisodes/releases/new)?

**Comment by Lextuga007** [comment]
v0.0.1 rather than v0.1.0? I've only used the third place for patches.

**Comment by Lextuga007** [comment]
😄 it is a bit late that's true!
